# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type_of_scholorship', models.CharField(choices=[('national', 'National'), ('state', 'State')], max_length=128)),
                ('stream', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('be', 'Bachelor of Engineering (BE)'), ('ba', 'Bachelor of Arts (BA)'), ('mbbs', 'Bachelor of Medicine and Bachelor of Surgery (MBBS)'), ('bba', 'Bachelor of Business Administration (BBA)')], max_length=256)),
                ('income', models.CharField(choices=[('0-100000', '0-100000'), ('100001-250000', '100000-250000'), ('250001-400000', '400001-600000'), ('600001 and above', '600001 and above')], max_length=256)),
                ('caste', models.CharField(choices=[('open', 'Open'), ('sebc', 'SEBC'), ('sc', 'SC'), ('st', 'ST')], max_length=128)),
            ],
        ),
    ]
