# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=250)),
                ('metadata', models.TextField(max_length=500)),
                ('context', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
