# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='metadata',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
