# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180308_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
